# Generated by Django 5.0.7 on 2024-07-23 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("user_name", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=120)),
                ("password", models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name="Todo",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=120)),
                ("description", models.TextField()),
                ("completed", models.BooleanField(default=False)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="todo_api.user"
                    ),
                ),
            ],
        ),
    ]
